import enum

class EnvelopeType(enum.Enum):
    # user <-> server 
    USER_HELLO = "USER_HELLO"
    MSG_DIRECT = "MSG_DIRECT"
    MSG_PUBLIC_CHANNEL = "MSG_PUBLIC_CHANNEL"
    FILE_START = "FILE_START"
    FILE_CHUNK = "FILE_CHUNK"
    FILE_END = "FILE_END"
    USER_DELIVER = "USER_DELIVER"

    REGISTER = "REGISTER"
    LOGIN = "LOGIN"

    REGISTER_RESPONSE = "REGISTER_RESPONSE"
    LOGIN_RESPONSE = "LOGIN_RESPONSE"

    # server <-> server
    SERVER_HELLO_JOIN = "SERVER_HELLO_JOIN"
    SERVER_WELCOME = "SERVER_WELCOME"
    SERVER_ANNOUNCE = "SERVER_ANNOUNCE"
    USER_ADVERTISE = "USER_ADVERTISE"
    USER_REMOVE = "USER_REMOVE"
    SERVER_DELIVER = "SERVER_DELIVER"
    HEARTBEAT = "HEARTBEAT"

    # common
    ACK = "ACK"
    ERROR = "ERROR"